apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-achat-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-achat
  template:
    metadata:
      labels:
        app: test-achat
    spec:
      containers:
        - name: test-achat
          image: eyabahri14/testachat:latest
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/achatdb?autoReconnect=true&failOverReadOnly=false&maxReconnects=10"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 8089
