version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=191JFT4899Aa_
      - MYSQL_DATABASE=achatdb
      - MYSQL_PASSWORD=191JFT4899Aa_
    ports:
      - '3307:3306'
    volumes:
      - db_vol:/var/lib/mysql:rw
  backend:
    container_name: 'backendserver'
    image: eyabahri14/testachat
    ports:
      - '8089:8089'
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/achatdb?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=191JFT4899Aa_
    depends_on:
      - mysqldb

volumes:
  db_vol: {}